### PR TITLE
Upgrade FTXUI version.

### PR DESCRIPTION
**Pull request by ArthurSonzogni**
Upgrade the FTXUI version from patch 208 to patch 261.

There were no breaking change affecting hastur, since it was only using
the dom/ and screen/ subcomponent.

### CODE REVIEW

**Comment by robinlinden** [comment]
Thank you, looks good! Seems like there's a GitHub Actions outage right now: 
image
but I'll merge this once CI has passed. I'll probably update the commit message so it doesn't use `#123` links though, since those will point to random issues/PRs in this repo as opposed to the FTXUI-repo. :P

**Review by robinlinden — APPROVED** [review]

**Comment by robinlinden** [comment]
Do you know if any of these warnings have been resolved in master? It looks like maybe the top one has been fixed at least?
https://github.com/robinlinden/hastur/blob/7639020afd83635d9b7dd154ec1e6b16fc32accb/.bazelrc#L54-L56
https://github.com/robinlinden/hastur/blob/7639020afd83635d9b7dd154ec1e6b16fc32accb/.bazelrc#L32

If not, I can have a look at fixing them if you want. None of them looked like they would cause any actual bugs when I had a look, so I just disabled them for ftxui, so it's probably not a big deal either way.

**Comment by ArthurSonzogni** [comment]
> Do you know if any of these warnings have been resolved in master? It looks like maybe the top one has been fixed at least?

Yes, it compiles without the first 3 exception, but not the one with `-Wno-shadow`.

I will update FTXUI to pass `-Wno-shadow' ` and update this patch after.

**Comment by robinlinden** [comment]
No rush, and I don't mind doing it either. :P Not a lot of projects use the insane amount of warnings I've stuck into this one, and as you can see from that file, FTXUI is one of the dependencies with the least warnings. :D

**Comment by ArthurSonzogni** [comment]
I am done with `-Wshadow.`
I updated FTXUI version and removed all the babelrc exception.

**Comment by robinlinden** [comment]
Awesome, thank you! I tried restarting the queued GitHub Actions runs, but it seems they're still having issues. :/

**Comment by ArthurSonzogni** [comment]
> Awesome, thank you! I tried restarting the queued GitHub Actions runs, but it seems they're still having issues. :/

Yes, the FTXUI workflow are permanently queued on my side too. Happy to discover this outage was external to me.

**Comment by robinlinden** [comment]
Looks like some of the MSVC warning disables were necessary after all: https://github.com/robinlinden/hastur/pull/12/checks?check_run_id=2596058799#step:4:36

**Comment by ArthurSonzogni** [comment]
> Looks like some of the MSVC warning disables were necessary after all: https://github.com/robinlinden/hastur/pull/12/checks?check_run_id=2596058799#step:4:36

I added them back.

**Review by robinlinden — APPROVED** [review]
Great, thank you!

**Pull request merged**
