### PR TITLE
Use string_view in trim functions

### PR DESCRIPTION
**Pull request by mkiael**
This commit changes to use string_view in all trim functions. Also made these function constexpr.

### CODE REVIEW

**Comment by mkiael** [comment]
Forgot to add tests for `is_whitespace()`. Will fix.

**Review by robinlinden — APPROVED** [review]
Looks good! I think you can get rid of the `<string>` and `<utility>` includes from `util/string.h` now as well?

**Review by robinlinden — APPROVED** [review]
Rebase instead of merging when updating the PR against master (I think I asked GitHub to require a linear history, so hopefully it can't even be merged with merge commits?), and I think it's nicer to add the unit test in the same commit as you added the feature you're testing.

**Comment by mkiael** [comment]
Sorry, got a bit messy. Fixed now!

**Pull request merged**
