### PR TITLE
ci: Update Buildifier and codecov

### PR DESCRIPTION
**Pull request by robinlinden**
https://github.com/bazelbuild/buildtools/releases/tag/6.1.0

### CODE REVIEW

**Review by GrayHatter — APPROVED** [review]
we should talk about pulling random bins down into the build system before we start releasing builds. But that's future you's problem. :P

**Comment by robinlinden** [comment]
> pulling random bins down into the build system

...you mean the linters and code coverage uploader that are only used in the CI?

**Comment by GrayHatter** [comment]
> ...you mean the linters

wow buildifer is a horrible name for a linter :<

yes... seems that's what I mean

**Comment by robinlinden** [comment]
Yeah, it's not obvious **Build**ifier's a linter unless you know about it previously. :P It formats and lints our Bazel build files.

**Review by Zer0-One — APPROVED** [review]

**Pull request merged**
